FROM python:image_and_tag

RUN mkdir /libs /out

COPY requirements.txt /
RUN pip install --upgrade pip && pip install --target /libs/ -r /requirements.txt && rm /requirements.txt
RUN tar cvf /libs.tar /libs/
RUN pip freeze > /installed_libs.txt
